// components/Sidebar.vue
<template>
  <div class="fixed left-0 top-0 h-screen w-64 bg-neutral-900 text-white flex flex-col">
    <!-- Logo Section -->
    <div class="p-6 border-b border-neutral-700">
      <img
        src="/assets/rialtic_logo_white.svg"
        alt="Rialtic"
        class="h-8 w-auto"
      />
    </div>

    <!-- Practice Selector -->
    <div class="p-4">
      <select
        v-model="selectedPractice"
        class="w-full px-3 py-2 bg-neutral-800 border border-neutral-700 text-white rounded-lg focus:outline-none focus:ring-2 focus:ring-secondary-500 text-sm"
      >
        <option value="practice-1">Main Practice</option>
      </select>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 px-3 overflow-y-auto">
      <NuxtLink
        v-for="item in navItems"
        :key="item.id"
        :to="item.path"
        class="w-full flex items-center gap-3 px-3 py-2.5 mb-1 rounded-lg text-sm transition-colors no-underline"
        :class="isActive(item.path)
          ? 'bg-primary-600 text-white'
          : 'text-neutral-300 hover:bg-neutral-800 hover:text-white'"
      >
        <Icon :name="item.icon" class="w-5 h-5 flex-shrink-0" />
        <span>{{ item.label }}</span>
      </NuxtLink>
    </nav>

    <!-- Footer -->
    <div class="p-4 border-t border-neutral-700">
      <button class="flex items-center gap-2 text-neutral-400 hover:text-white text-sm transition-colors">
        <Icon name="heroicons:book-open" class="w-4 h-4" />
        <span>Product Guide</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
const route = useRoute()
const selectedPractice = ref('practice-1')

const navItems = [
  { id: 'dashboard', label: 'Dashboard', icon: 'heroicons:squares-2x2', path: '/' },
  { id: 'policies', label: 'Policies', icon: 'heroicons:document-text', path: '/policies' },
  { id: 'claims', label: 'Claims', icon: 'heroicons:clipboard-document-list', path: '/claims' },
  { id: 'insights', label: 'Insights', icon: 'heroicons:light-bulb', path: '/insights' },
  { id: 'claim-lab', label: 'Claim Lab', icon: 'heroicons:beaker', path: '/claim-lab' },
  { id: 'impact', label: 'Impact', icon: 'heroicons:chart-bar', path: '/impact' },
]

function isActive(path: string): boolean {
  if (path === '/' && route.path === '/') return true
  if (path !== '/' && route.path.startsWith(path)) return true
  return false
}
</script>

<style scoped>
a {
  text-decoration: none;
}
</style>

// src/components/Layout/Sidebar.jsx
import React from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { LayoutDashboard, FileText, ClipboardList, Lightbulb, FlaskConical, BookOpen, TrendingUp } from 'lucide-react';
import { Select } from '../shared/Select';

export const Sidebar = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const navItems = [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/dashboard' },
    { id: 'policies', label: 'Policies', icon: FileText, path: '/policies' },
    { id: 'claims', label: 'Claims', icon: ClipboardList, path: '/claims' },
    { id: 'insights', label: 'Insights', icon: Lightbulb, path: '/insights' },
    { id: 'claim-lab', label: 'Claim Lab', icon: FlaskConical, path: '/claim-lab' },
    { id: 'impact', label: 'Impact', icon: TrendingUp, path: '/impact' }
  ];

  const practiceOptions = [
    { value: 'practice-1', label: 'Main Practice' }
  ];

  return (
    <div className="fixed left-0 top-0 h-screen w-64 bg-gradient-to-b from-indigo-600 to-indigo-700 text-white flex flex-col">
      <div className="p-6">
        <div className="w-12 h-12 bg-white rounded-lg flex items-center justify-center mb-6">
          <span className="text-indigo-600 font-bold text-2xl">R</span>
        </div>

        <Select
          value="practice-1"
          onChange={() => {}}
          options={practiceOptions}
          className="bg-indigo-500 border-indigo-400 text-white mb-6"
        />
      </div>

      <nav className="flex-1 px-3">
        {navItems.map((item) => {
          const Icon = item.icon;
          const isActive = location.pathname === item.path ||
                          (item.path === '/dashboard' && location.pathname === '/');
          return (
            <button
              key={item.id}
              onClick={() => navigate(item.path)}
              className={`w-full flex items-center gap-3 px-3 py-3 mb-1 rounded-lg text-sm transition-colors ${
                isActive
                  ? 'bg-indigo-500 text-white'
                  : 'text-indigo-100 hover:bg-indigo-500/50'
              }`}
            >
              <Icon className="w-5 h-5" />
              <span>{item.label}</span>
            </button>
          );
        })}
      </nav>

      <div className="p-6 border-t border-indigo-500">
        <button className="flex items-center gap-2 text-indigo-100 hover:text-white text-sm transition-colors">
          <BookOpen className="w-4 h-4" />
          <span>Product Guide</span>
        </button>
      </div>
    </div>
  );
};
