// src/components/shared/Card.jsx
import React from 'react';

export const Card = ({ children, className = '', hover = false, onClick }) => {
  const baseStyles = 'bg-white border border-gray-200 rounded-lg shadow-sm';
  const hoverStyles = hover ? 'hover:shadow-md transition-shadow cursor-pointer' : '';

  return (
    <div
      className={`${baseStyles} ${hoverStyles} ${className}`}
      onClick={onClick}
    >
      {children}
    </div>
  );
};

// components/ui/Card.vue
<script setup lang="ts">
/**
 * Card component aligned with console-ui patterns
 * Standard container with consistent styling
 */
defineProps<{
  padding?: 'none' | 'sm' | 'md' | 'lg'
  shadow?: boolean
  hoverable?: boolean
}>()
</script>

<template>
  <div
    class="bg-white rounded-lg border border-neutral-200"
    :class="{
      'p-0': padding === 'none',
      'p-4': padding === 'sm',
      'p-6': padding === 'md' || !padding,
      'p-8': padding === 'lg',
      'shadow-sm': shadow !== false,
      'hover:border-primary-300 hover:shadow-md transition-all cursor-pointer': hoverable,
    }"
  >
    <slot />
  </div>
</template>
